- name: latest Apache version installed
  yum:
    name: httpd
    state: latest
  notify: apache-restart
 
- name: Apache enabled and running
  service:
    name: httpd
    enabled: true
    state: started
 
- name: Create Apache Document Root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "apache"
    group: "apache"
    mode: '0755'
 
- name: Set up Apache VirtualHost
  template:
    src: "files/httpd.conf"
    dest: "/etc/httpd/conf.d/{{ http_conf }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
